### ISSUE TITLE
Gallery Images

### ISSUE THREAD

**Issue by nuotsu** [ASokry/Utopia#1]
Add the following in `main.css` to adjust the width of the gallery images in `gallery.html`, which helps to center them on screen:

```css
img.image_control {
	width: 100%;
}
```

_poop_

--Mitchell 💩
